In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("./data/house_prices.csv")

In [3]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [4]:
df.iloc[2,4]

0.469

In [5]:
df.iloc[3,5]

6.998

In [6]:
df.iloc[2,3] + df.iloc[4,5]

7.147

In [7]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [8]:
df['CRIM']

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...   
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: CRIM, Length: 506, dtype: float64

In [9]:
df['NOX']

0      0.538
1      0.469
2      0.469
3      0.458
4      0.458
       ...  
501    0.573
502    0.573
503    0.573
504    0.573
505    0.573
Name: NOX, Length: 506, dtype: float64

In [10]:
df['CRIM'] + df['NOX']

0      0.54432
1      0.49631
2      0.49629
3      0.49037
4      0.52705
        ...   
501    0.63563
502    0.61827
503    0.63376
504    0.68259
505    0.62041
Length: 506, dtype: float64

In [11]:
A = np.array([1,2,3,4,5,6,7,8])
print(A)

[1 2 3 4 5 6 7 8]


In [12]:
#행벡터를 열벡터를 바꿔주는 코드.
A1 = A.reshape(8,1)

In [13]:
print(A1)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [14]:

print(A.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
A = np.array([[2,7],[3,4],[5,2]])
B = np.array([[3,-3,5],[-1,2,1]])
C = A.dot(B)
print(C)

[[ -1   8  17]
 [  5  -1  19]
 [ 13 -11  27]]


In [27]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [31]:
X = df[['CRIM','NOX','RM','AGE','TAX']]
X

CRIM    NOX     RM   AGE  TAX
0    0.00632  0.538  6.575  65.2  296
1    0.02731  0.469  6.421  78.9  242
2    0.02729  0.469  7.185  61.1  242
3    0.03237  0.458  6.998  45.8  222
4    0.06905  0.458  7.147  54.2  222
..       ...    ...    ...   ...  ...
501  0.06263  0.573  6.593  69.1  273
502  0.04527  0.573  6.120  76.7  273
503  0.06076  0.573  6.976  91.0  273
504  0.10959  0.573  6.794  89.3  273
505  0.04741  0.573  6.030  80.8  273

[506 rows x 5 columns]

In [34]:
X_t = np.transpose(X)
X_t

0          1          2          3          4          5    \
CRIM    0.00632    0.02731    0.02729    0.03237    0.06905    0.02985   
NOX     0.53800    0.46900    0.46900    0.45800    0.45800    0.45800   
RM      6.57500    6.42100    7.18500    6.99800    7.14700    6.43000   
AGE    65.20000   78.90000   61.10000   45.80000   54.20000   58.70000   
TAX   296.00000  242.00000  242.00000  222.00000  222.00000  222.00000   

            6          7          8          9    ...       496        497  \
CRIM    0.08829    0.14455    0.21124    0.17004  ...    0.2896    0.26838   
NOX     0.52400    0.52400    0.52400    0.52400  ...    0.5850    0.58500   
RM      6.01200    6.17200    5.63100    6.00400  ...    5.3900    5.79400   
AGE    66.60000   96.10000  100.00000   85.90000  ...   72.9000   70.60000   
TAX   311.00000  311.00000  311.00000  311.00000  ...  391.0000  391.00000   

            498        499        500        501        502        503  \
CRIM    0.23912    0.17783    0.22438    0.06263    0.04527    0.06076   
NOX     0.58500    0.58500    0.58500    0.57300    0.57300    0.57300   
RM      6.01900    5.56900    6.02700    6.59300    6.12000    6.97600   
AGE    65.30000   73.50000   79.70000   69.10000   76.70000   91.00000   
TAX   391.00000  391.00000  391.00000  273.00000  273.00000  273.00000   

            504        505  
CRIM    0.10959    0.04741  
NOX     0.57300    0.57300  
RM      6.79400    6.03000  
AGE    89.30000   80.80000  
TAX   273.00000  273.00000  

[5 rows x 506 columns]

In [35]:
X_t2 = X.T
X_t2

0          1          2          3          4          5    \
CRIM    0.00632    0.02731    0.02729    0.03237    0.06905    0.02985   
NOX     0.53800    0.46900    0.46900    0.45800    0.45800    0.45800   
RM      6.57500    6.42100    7.18500    6.99800    7.14700    6.43000   
AGE    65.20000   78.90000   61.10000   45.80000   54.20000   58.70000   
TAX   296.00000  242.00000  242.00000  222.00000  222.00000  222.00000   

            6          7          8          9    ...       496        497  \
CRIM    0.08829    0.14455    0.21124    0.17004  ...    0.2896    0.26838   
NOX     0.52400    0.52400    0.52400    0.52400  ...    0.5850    0.58500   
RM      6.01200    6.17200    5.63100    6.00400  ...    5.3900    5.79400   
AGE    66.60000   96.10000  100.00000   85.90000  ...   72.9000   70.60000   
TAX   311.00000  311.00000  311.00000  311.00000  ...  391.0000  391.00000   

            498        499        500        501        502        503  \
CRIM    0.23912    0.17783    0.22438    0.06263    0.04527    0.06076   
NOX     0.58500    0.58500    0.58500    0.57300    0.57300    0.57300   
RM      6.01900    5.56900    6.02700    6.59300    6.12000    6.97600   
AGE    65.30000   73.50000   79.70000   69.10000   76.70000   91.00000   
TAX   391.00000  391.00000  391.00000  273.00000  273.00000  273.00000   

            504        505  
CRIM    0.10959    0.04741  
NOX     0.57300    0.57300  
RM      6.79400    6.03000  
AGE    89.30000   80.80000  
TAX   273.00000  273.00000  

[5 rows x 506 columns]

In [36]:
#행렬곱
X_t.dot(X)

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [37]:
#공분산 행렬
X_t@X

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [38]:
XtX = X_t@X

In [39]:
np.linalg.det(XtX)

7.91431657769047e+21

In [40]:
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 4.07613803e-05  1.32526683e-04  4.76832932e-05 -1.01889386e-06
  -1.10744437e-06]
 [ 1.32526683e-04  3.44301609e-01 -1.30762150e-02 -8.56047279e-04
  -1.21234099e-04]
 [ 4.76832932e-05 -1.30762150e-02  9.05341934e-04  1.73338529e-05
   1.03814433e-06]
 [-1.01889386e-06 -8.56047279e-04  1.73338529e-05  5.35211609e-06
   4.19638894e-09]
 [-1.10744437e-06 -1.21234099e-04  1.03814433e-06  4.19638894e-09
   1.58047038e-07]]


In [41]:
XtX @ XtX_inv

0             1             2             3             4
CRIM  1.000000e+00 -7.643977e-14 -1.381674e-15 -4.241093e-16  5.193812e-17
NOX  -8.856692e-18  1.000000e+00  2.420336e-16  1.163556e-17 -2.476682e-18
RM    1.730192e-16 -4.334970e-15  1.000000e+00 -1.261543e-16 -2.928635e-17
AGE   6.126108e-16 -6.351444e-13  4.884368e-14  1.000000e+00 -2.194000e-16
TAX   2.829222e-15  4.488510e-13  1.467297e-14 -6.681938e-15  1.000000e+00

In [42]:
XtX_inv @ XtX

CRIM           NOX            RM           AGE           TAX
0  1.000000e+00 -1.908474e-16 -2.440727e-15 -2.841986e-14 -1.216970e-13
1 -2.343027e-13  1.000000e+00 -2.188506e-13 -1.946254e-12 -1.407552e-11
2  1.156221e-14  6.227042e-16  1.000000e+00  7.401608e-14  4.504880e-13
3  5.615874e-16  5.415753e-17  7.001283e-16  1.000000e+00  5.473713e-14
4  2.418254e-17  2.123092e-18  5.398038e-17  9.681858e-16  1.000000e+00

In [43]:
crim = df['CRIM']
nox = df['NOX']

In [44]:
res = np.inner(crim,nox)
print(res)

1226.123170231


In [45]:
#고유값과 고유벡터
e, v = np.linalg.eig(X_t.dot(X))

In [46]:
#고유값이 큰 순서대로 나온다.
e

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [47]:
v

array([[ 1.17248568e-02, -4.34541539e-02, -9.89273583e-01,
         1.38967257e-01, -3.78876853e-04],
       [ 1.21545113e-03,  3.97729110e-03,  5.48368537e-03,
         3.74537281e-02, -9.99274663e-01],
       [ 1.28461807e-02,  4.11504926e-02,  1.37240647e-01,
         9.88869506e-01,  3.79962757e-02],
       [ 1.54544362e-01,  9.86199762e-01, -4.66395497e-02,
        -3.66695593e-02,  2.48287726e-03],
       [ 9.87832003e-01, -1.54313263e-01,  1.72471505e-02,
        -8.81831838e-03,  3.51466736e-04]])

In [48]:
#특이값 분해
u, s, vt = np.linalg.svd(X_t.dot(X))

In [49]:
u

array([[-1.17248568e-02,  4.34541539e-02,  9.89273583e-01,
        -1.38967257e-01, -3.78876853e-04],
       [-1.21545113e-03, -3.97729110e-03, -5.48368537e-03,
        -3.74537281e-02, -9.99274663e-01],
       [-1.28461807e-02, -4.11504926e-02, -1.37240647e-01,
        -9.88869506e-01,  3.79962757e-02],
       [-1.54544362e-01, -9.86199762e-01,  4.66395497e-02,
         3.66695593e-02,  2.48287726e-03],
       [-9.87832003e-01,  1.54313263e-01, -1.72471505e-02,
         8.81831838e-03,  3.51466736e-04]])

In [50]:
# 고윳값
s

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [51]:
vt

array([[-1.17248568e-02, -1.21545113e-03, -1.28461807e-02,
        -1.54544362e-01, -9.87832003e-01],
       [ 4.34541539e-02, -3.97729110e-03, -4.11504926e-02,
        -9.86199762e-01,  1.54313263e-01],
       [ 9.89273583e-01, -5.48368537e-03, -1.37240647e-01,
         4.66395497e-02, -1.72471505e-02],
       [-1.38967257e-01, -3.74537281e-02, -9.88869506e-01,
         3.66695593e-02,  8.81831838e-03],
       [-3.78876853e-04, -9.99274663e-01,  3.79962757e-02,
         2.48287726e-03,  3.51466736e-04]])

In [53]:
u2, s2, vt2 = np.linalg.svd(X)

In [54]:
u2

array([[-0.03008946,  0.03086023,  0.01712144, ..., -0.00411115,
        -0.00427013, -0.00365704],
       [-0.02499491,  0.06652264,  0.00780423, ..., -0.05447262,
        -0.05387641, -0.05180949],
       [-0.02472231,  0.03790476,  0.0132068 , ..., -0.01726598,
        -0.01167245,  0.01252377],
       ...,
       [-0.02822706,  0.07823426,  0.00788495, ...,  0.99280739,
        -0.00687219, -0.00535758],
       [-0.02820076,  0.07548049,  0.00791964, ..., -0.00689953,
         0.99336613, -0.00536756],
       [-0.02806907,  0.0617432 ,  0.00995976, ..., -0.00551636,
        -0.00549819,  0.99463978]])

In [55]:
s2

array([1.00553387e+04, 6.12306718e+02, 1.73076199e+02, 4.90216487e+01,
       1.70300420e+00])

In [56]:
vt2

array([[-1.17248568e-02, -1.21545113e-03, -1.28461807e-02,
        -1.54544362e-01, -9.87832003e-01],
       [-4.34541539e-02,  3.97729110e-03,  4.11504926e-02,
         9.86199762e-01, -1.54313263e-01],
       [-9.89273583e-01,  5.48368537e-03,  1.37240647e-01,
        -4.66395497e-02,  1.72471505e-02],
       [-1.38967257e-01, -3.74537281e-02, -9.88869506e-01,
         3.66695593e-02,  8.81831838e-03],
       [-3.78876853e-04, -9.99274663e-01,  3.79962757e-02,
         2.48287726e-03,  3.51466736e-04]])