In [1]:
import pandas as pd
df = pd.read_csv("./data/wine_data.csv")

In [2]:
df

Alcohol  Malic   Ash  Alcalinity  Magesium  Phenols  Flavanoids  \
0      14.23   1.71  2.43        15.6       127     2.80        3.06   
1      13.20   1.78  2.14        11.2       100     2.65        2.76   
2      13.16   2.36  2.67        18.6       101     2.80        3.24   
3      14.37   1.95  2.50        16.8       113     3.85        3.49   
4      13.24   2.59  2.87        21.0       118     2.80        2.69   
..       ...    ...   ...         ...       ...      ...         ...   
173    13.71   5.65  2.45        20.5        95     1.68        0.61   
174    13.40   3.91  2.48        23.0       102     1.80        0.75   
175    13.27   4.28  2.26        20.0       120     1.59        0.69   
176    13.17   2.59  2.37        20.0       120     1.65        0.68   
177    14.13   4.10  2.74        24.5        96     2.05        0.76   

     Nonflavanoids  Proanthocyanins  Color   Hue  Dilution  Proline  class  
0             0.28             2.29   5.64  1.04      3.92     1065      0  
1             0.26             1.28   4.38  1.05      3.40     1050      0  
2             0.30             2.81   5.68  1.03      3.17     1185      0  
3             0.24             2.18   7.80  0.86      3.45     1480      0  
4             0.39             1.82   4.32  1.04      2.93      735      0  
..             ...              ...    ...   ...       ...      ...    ...  
173           0.52             1.06   7.70  0.64      1.74      740      2  
174           0.43             1.41   7.30  0.70      1.56      750      2  
175           0.43             1.35  10.20  0.59      1.56      835      2  
176           0.53             1.46   9.30  0.60      1.62      840      2  
177           0.56             1.35   9.20  0.61      1.60      560      2  

[178 rows x 14 columns]

In [3]:
df.columns

Index(['Alcohol', 'Malic', 'Ash', 'Alcalinity', 'Magesium', 'Phenols',
       'Flavanoids', 'Nonflavanoids', 'Proanthocyanins', 'Color', 'Hue',
       'Dilution', 'Proline', 'class'],
      dtype='object')

In [4]:
features = ['Alcohol', 'Malic', 'Ash', 'Alcalinity', 'Magesium', 'Phenols', 'Flavanoids', 'Nonflavanoids', 'Proanthocyanins', 'Color', 'Hue', 'Dilution', 'Proline']

X = df[features]
y = df['class']

In [23]:
#가설 검정
XTX = X.T.dot(X)
XTX

Alcohol          Malic            Ash    Alcalinity  \
Alcohol          3.020151e+04    5421.720200    5484.719700  4.496457e+04   
Malic            5.421720e+03    1192.515900     993.062400  8.297873e+03   
Ash              5.484720e+03     993.062400    1010.193400  8.283949e+03   
Alcalinity       4.496457e+04    8297.873000    8283.949000  6.962343e+04   
Magesium         2.313687e+05   41325.400000   42213.900000  3.454097e+05   
Phenols          5.337141e+03     912.990600     970.712900  7.845476e+03   
Flavanoids       4.729943e+03     762.734800     860.391200  6.834310e+03   
Nonflavanoids    8.345813e+02     157.694000     153.552800  1.282294e+03   
Proanthocyanins  3.692758e+03     636.624100     670.418500  5.453818e+03   
Color            1.188698e+04    2217.644198    2159.813598  1.757775e+04   
Hue              2.213287e+03     372.805860     402.487260  3.285431e+03   
Dilution         6.051108e+03    1034.358400    1100.281200  8.946656e+03   
Proline          1.757522e+06  298654.350000  318040.910000  2.509780e+06   

                     Magesium        Phenols     Flavanoids  Nonflavanoids  \
Alcohol          2.313687e+05    5337.141500    4729.943100      834.58130   
Malic            4.132540e+04     912.990600     762.734800      157.69400   
Ash              4.221390e+04     970.712900     860.391200      153.55280   
Alcalinity       3.454097e+05    7845.476000    6834.310000     1282.29400   
Magesium         1.806918e+06   41086.640000   36522.030000     6343.72000   
Phenols          4.108664e+04    1006.951300     924.680800      141.62520   
Flavanoids       3.652203e+04     924.680800     909.588700      118.86980   
Nonflavanoids    6.343720e+03     141.625200     118.869800       26.04850   
Proanthocyanins  2.858693e+04     688.759000     640.695700       97.85720   
Color            9.097316e+04    2052.221899    1756.379799      332.89290   
Hue              1.703057e+04     402.127700     367.802820       60.34692   
Dilution         4.648633e+04    1122.002600    1042.179300      160.34760   
Proline          1.357348e+07  322504.580000  297299.520000    45947.36000   

                 Proanthocyanins          Color            Hue       Dilution  \
Alcohol              3692.757600   11886.982387    2213.286840    6051.107800   
Malic                 636.624100    2217.644198     372.805860    1034.358400   
Ash                   670.418500    2159.813598     402.487260    1100.281200   
Alcalinity           5453.818000   17577.746981    3285.431400    8946.656000   
Magesium            28586.930000   90973.159914   17030.568000   46486.330000   
Phenols               688.759000    2052.221899     402.127700    1122.002600   
Flavanoids            640.695700    1756.379799     367.802820    1042.179300   
Nonflavanoids          97.857200     332.892900      60.346920     160.347600   
Proanthocyanins       508.495000    1426.419699     277.974160     776.912200   
Color                1426.419699    5505.278180     813.088499    2226.475998   
Hue                   277.974160     813.088499     172.421636     461.341720   
Dilution              776.912200    2226.475998     461.341720    1303.343600   
Proline            222046.350000  713303.719530  130299.070000  359592.910000   

                      Proline  
Alcohol          1.757522e+06  
Malic            2.986543e+05  
Ash              3.180409e+05  
Alcalinity       2.509780e+06  
Magesium         1.357348e+07  
Phenols          3.225046e+05  
Flavanoids       2.972995e+05  
Nonflavanoids    4.594736e+04  
Proanthocyanins  2.220464e+05  
Color            7.133037e+05  
Hue              1.302991e+05  
Dilution         3.595929e+05  
Proline          1.168497e+08

In [31]:
import numpy as np
import pandas as pd
X_cov = cov(X)

NameError: name 'cov' is not defined

In [5]:
from sklearn.model_selection import train_test_split
X_tn, X_te, y_tn, y_te = train_test_split(X,y,random_state = 0,train_size = 0.6,test_size = 0.4)

In [6]:
from sklearn.preprocessing import StandardScaler
std_scale = StandardScaler()
std_scale.fit(X_tn)
X_tn_std = std_scale.transform(X_tn)
X_te_std = std_scale.transform(X_te)

In [7]:
from sklearn.linear_model import LogisticRegression
clf_logi_l2= LogisticRegression(penalty = 'l2')
clf_logi_l2.fit(X_tn_std,y_tn)

LogisticRegression()

In [9]:
print(clf_logi_l2.coef_)
print(clf_logi_l2.intercept_)

[[ 0.69853977  0.25867826  0.39868195 -0.76815236 -0.00429211  0.18526119
   0.74915884 -0.12654939  0.10401364  0.17318889  0.13724279  0.68065574
   0.98907933]
 [-0.81533159 -0.47295284 -0.74058812  0.54948684 -0.08525548  0.01376966
   0.18741135  0.13017416  0.324744   -1.07084932  0.57591149  0.1276171
  -0.99183488]
 [ 0.11679181  0.21427458  0.34190617  0.21866552  0.08954759 -0.19903085
  -0.93657019 -0.00362477 -0.42875763  0.89766042 -0.71315428 -0.80827284
   0.00275554]]
[ 0.29606777  0.57687138 -0.87293914]


In [11]:
pred_logistic = clf_logi_l2.predict(X_te_std)
print(pred_logistic)

[0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


In [14]:
pred_proba = clf_logi_l2.predict_proba(X_te_std)
print(pred_proba)

[[9.93360060e-01 4.92359807e-03 1.71634194e-03]
 [3.22076323e-04 2.77943948e-04 9.99399980e-01]
 [1.00535859e-02 9.89854907e-01 9.15071461e-05]
 [9.85578241e-01 1.15830075e-02 2.83875127e-03]
 [9.72825954e-02 8.94560998e-01 8.15640637e-03]
 [1.60778757e-01 8.37805552e-01 1.41569030e-03]
 [9.99185889e-01 2.82861666e-04 5.31249532e-04]
 [9.27747541e-04 6.79471537e-03 9.92277537e-01]
 [4.73077770e-03 9.94412333e-01 8.56889586e-04]
 [1.16783305e-03 9.96547896e-01 2.28427103e-03]
 [2.29360201e-02 1.70472078e-02 9.60016772e-01]
 [5.37945912e-04 2.05426668e-03 9.97407787e-01]
 [9.99868646e-01 4.18491948e-05 8.95049101e-05]
 [7.05474922e-02 9.29254258e-01 1.98249912e-04]
 [3.43785273e-03 1.00980993e-03 9.95552337e-01]
 [1.23126171e-04 9.99870752e-01 6.12188768e-06]
 [9.95131651e-01 3.26254700e-03 1.60580153e-03]
 [9.99969651e-01 5.43181185e-06 2.49174273e-05]
 [5.79978522e-03 7.64925188e-01 2.29275027e-01]
 [9.98986465e-01 9.25988748e-04 8.75463768e-05]
 [6.06195463e-02 9.39306550e-01 7.390404

In [15]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_te, pred_logistic)
print(accuracy)

1.0


In [16]:
from sklearn.metrics import precision_score
precision = precision_score(y_te,pred_logistic, average = 'macro')
print(precision)

1.0


In [17]:
from sklearn.metrics import recall_score
recall = recall_score(y_te,pred_logistic, average = 'macro')
print(recall)

1.0


In [18]:
from sklearn.metrics import f1_score
f1 = f1_score(y_te,pred_logistic, average = 'macro')
print(f1)

1.0


In [19]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te, pred_logistic)
print(conf_matrix)

[[16  0  0]
 [ 0 21  0]
 [ 0  0  8]]


In [20]:
from sklearn.metrics import classification_report
class_report = classification_report(y_te,pred_logistic)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00         8

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

