In [1]:
import pandas as pd
df = pd.read_csv("./data/wine_data.csv")
df

Alcohol  Malic   Ash  Alcalinity  Magesium  Phenols  Flavanoids  \
0      14.23   1.71  2.43        15.6       127     2.80        3.06   
1      13.20   1.78  2.14        11.2       100     2.65        2.76   
2      13.16   2.36  2.67        18.6       101     2.80        3.24   
3      14.37   1.95  2.50        16.8       113     3.85        3.49   
4      13.24   2.59  2.87        21.0       118     2.80        2.69   
..       ...    ...   ...         ...       ...      ...         ...   
173    13.71   5.65  2.45        20.5        95     1.68        0.61   
174    13.40   3.91  2.48        23.0       102     1.80        0.75   
175    13.27   4.28  2.26        20.0       120     1.59        0.69   
176    13.17   2.59  2.37        20.0       120     1.65        0.68   
177    14.13   4.10  2.74        24.5        96     2.05        0.76   

     Nonflavanoids  Proanthocyanins  Color   Hue  Dilution  Proline  class  
0             0.28             2.29   5.64  1.04      3.92     1065      0  
1             0.26             1.28   4.38  1.05      3.40     1050      0  
2             0.30             2.81   5.68  1.03      3.17     1185      0  
3             0.24             2.18   7.80  0.86      3.45     1480      0  
4             0.39             1.82   4.32  1.04      2.93      735      0  
..             ...              ...    ...   ...       ...      ...    ...  
173           0.52             1.06   7.70  0.64      1.74      740      2  
174           0.43             1.41   7.30  0.70      1.56      750      2  
175           0.43             1.35  10.20  0.59      1.56      835      2  
176           0.53             1.46   9.30  0.60      1.62      840      2  
177           0.56             1.35   9.20  0.61      1.60      560      2  

[178 rows x 14 columns]

In [2]:
features = ['Alcohol', 'Malic', 'Ash', 'Alcalinity', 'Magesium', 'Phenols',
       'Flavanoids', 'Nonflavanoids', 'Proanthocyanins', 'Color', 'Hue',
       'Dilution', 'Proline']
X = df[features]
y = df['class']

In [3]:
from sklearn.model_selection import train_test_split
X_tn, X_te,y_tn,y_te = train_test_split(X,y,random_state = 0)

In [4]:
from sklearn.preprocessing import StandardScaler
std_scale = StandardScaler()
std_scale.fit(X_tn)
X_tn_std = std_scale.transform(X_tn)
X_te_std = std_scale.transform(X_te)

In [8]:
from sklearn import svm
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV

param_grid = {'kernel' : ('linear', 'rbf'),
             'C' : [0.5, 1, 10, 100]}
kfold = StratifiedKFold(n_splits = 5, shuffle = True, random_state=0)
svc = svm.SVC(random_state = 0)
grid_cv = GridSearchCV(svc, param_grid, cv=kfold, scoring = 'accuracy')
grid_cv.fit(X_tn_std, y_tn)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=0, shuffle=True),
             estimator=SVC(random_state=0),
             param_grid={'C': [0.5, 1, 10, 100], 'kernel': ('linear', 'rbf')},
             scoring='accuracy')

In [9]:
grid_cv.cv_results_

{'mean_fit_time': array([0.00039878, 0.        , 0.00432158, 0.00179515, 0.00100937,
        0.00312514, 0.        , 0.00312943]),
 'std_fit_time': array([0.00079756, 0.        , 0.0056695 , 0.00039856, 0.00063128,
        0.00625029, 0.        , 0.00625887]),
 'mean_score_time': array([0.00287304, 0.        , 0.00052199, 0.00099745, 0.00019951,
        0.        , 0.        , 0.        ]),
 'std_score_time': array([5.16737219e-03, 0.00000000e+00, 4.48567018e-04, 4.42200589e-07,
        3.99017334e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 'param_C': masked_array(data=[0.5, 0.5, 1, 1, 10, 10, 100, 100],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=ob

In [10]:
import numpy as np
import pandas as pd

np.transpose(pd.DataFrame(grid_cv.cv_results_))

0  \
mean_fit_time                            0.000399   
std_fit_time                             0.000798   
mean_score_time                          0.002873   
std_score_time                           0.005167   
param_C                                       0.5   
param_kernel                               linear   
params             {'C': 0.5, 'kernel': 'linear'}   
split0_test_score                        0.888889   
split1_test_score                        0.962963   
split2_test_score                        0.925926   
split3_test_score                             1.0   
split4_test_score                        0.846154   
mean_test_score                          0.924786   
std_test_score                           0.054014   
rank_test_score                                 5   

                                             1                             2  \
mean_fit_time                              0.0                      0.004322   
std_fit_time                               0.0                       0.00567   
mean_score_time                            0.0                      0.000522   
std_score_time                             0.0                      0.000449   
param_C                                    0.5                             1   
param_kernel                               rbf                        linear   
params             {'C': 0.5, 'kernel': 'rbf'}  {'C': 1, 'kernel': 'linear'}   
split0_test_score                     0.962963                      0.888889   
split1_test_score                          1.0                      0.962963   
split2_test_score                     0.962963                      0.925926   
split3_test_score                     0.961538                           1.0   
split4_test_score                          1.0                      0.846154   
mean_test_score                       0.977493                      0.924786   
std_test_score                        0.018384                      0.054014   
rank_test_score                              1                             5   

                                           3                              4  \
mean_fit_time                       0.001795                       0.001009   
std_fit_time                        0.000399                       0.000631   
mean_score_time                     0.000997                         0.0002   
std_score_time                           0.0                       0.000399   
param_C                                    1                             10   
param_kernel                             rbf                         linear   
params             {'C': 1, 'kernel': 'rbf'}  {'C': 10, 'kernel': 'linear'}   
split0_test_score                   0.925926                       0.888889   
split1_test_score                   0.962963                       0.962963   
split2_test_score                   0.962963                       0.925926   
split3_test_score                   0.961538                            1.0   
split4_test_score                        1.0                       0.846154   
mean_test_score                     0.962678                       0.924786   
std_test_score                      0.023431                       0.054014   
rank_test_score                            2                              5   

                                            5                               6  \
mean_fit_time                        0.003125                             0.0   
std_fit_time                          0.00625                             0.0   
mean_score_time                           0.0                             0.0   
std_score_time                            0.0                             0.0   
param_C                                    10                             100   
param_kernel                              rbf                          linear   
params             {'C': 10, 'kernel': 'rbf'}  {'C': 100, 'kernel': 'linear'}   
split

In [11]:
grid_cv.best_score_

0.9774928774928775

In [12]:
grid_cv.best_params_

{'C': 0.5, 'kernel': 'rbf'}

In [13]:
clf = grid_cv.best_estimator_
print(clf)

SVC(C=0.5, random_state=0)


In [14]:
from sklearn.model_selection import cross_validate
metrics = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro']
cv_scores = cross_validate(clf,X_tn_std,y_tn,cv = kfold, scoring = metrics)
cv_scores

{'fit_time': array([0.00199485, 0.00199366, 0.00400138, 0.        , 0.00199437]),
 'score_time': array([0.00797749, 0.01509738, 0.00706935, 0.00862074, 0.00598407]),
 'test_accuracy': array([0.96296296, 1.        , 0.96296296, 0.96153846, 1.        ]),
 'test_precision_macro': array([0.96296296, 1.        , 0.96969697, 0.96969697, 1.        ]),
 'test_recall_macro': array([0.96666667, 1.        , 0.96296296, 0.95833333, 1.        ]),
 'test_f1_macro': array([0.9628483 , 1.        , 0.96451914, 0.96190476, 1.        ])}

In [15]:
from sklearn.model_selection import cross_val_score
cv_score = cross_val_score(clf, X_tn_std, y_tn, cv = kfold, scoring = 'accuracy')
print(cv_score)
print(cv_score.mean())
print(cv_score.std())

[0.96296296 1.         0.96296296 0.96153846 1.        ]
0.9774928774928775
0.01838434849561446


In [18]:
pred_svm = clf.predict(X_te_std)
print(pred_svm)

[0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


In [19]:
from sklearn.metrics import accuracy_score
accuracy =accuracy_score(y_te, pred_svm)
print(accuracy)

1.0


In [20]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te,pred_svm)
print(conf_matrix)

[[16  0  0]
 [ 0 21  0]
 [ 0  0  8]]


In [21]:
from sklearn.metrics import classification_report
class_report = classification_report(y_te,pred_svm)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00         8

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

